name: Issue to Markdown

on:
  issues:
    types: [opened, edited]

jobs:
  create_markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and commit markdown file
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        DIRECTORY_NAME=$(echo "$ISSUE_TITLE" | cut -d ']' -f 1 | tr -d '[')
        FILE_TITLE=$(echo "$ISSUE_TITLE" | cut -d ']' -f 2 | sed 's/^ *//')
        ISSUE_BODY="${{ github.event.issue.body }}"
        FILE_NAME="${FILE_TITLE// /_}.md"

        mkdir -p "$DIRECTORY_NAME"
        echo "# $FILE_TITLE" > "$DIRECTORY_NAME/$FILE_NAME"
        echo "" >> "$DIRECTORY_NAME/$FILE_NAME"
        IFS=$'\n' # 수정된 부분
        for line in $ISSUE_BODY; do
          ESCAPED_LINE=$(echo "$line" | sed 's//\\/g') # 수정된 부분
          printf '%s\n' "$ESCAPED_LINE" >> "$DIRECTORY_NAME/$FILE_NAME" # 수정된 부분
        done
        unset IFS # 수정된 부분
        git config --local user.email "${{ github.event.sender.email }}"
        git config --local user.name "${{ github.event.sender.login }}"
        git add "./$DIRECTORY_NAME/$FILE_NAME"
        git commit -m "Add markdown file for issue: $ISSUE_TITLE"
        git push

    - name: Close issue
      run: |
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
          -d '{"state": "closed"}'
